### ISSUE TITLE
Collide with reshade ?

### ISSUE THREAD

**Issue by d0ob** [AltimorTASDK/das3fov#3]
Hi there ! 
It doesn't work anymore since I installed reshade, any workaround maybe ? 
I'm sad because it's by far the most practical soft I found to change the fov !
Thanks, in any case.

**Comment by AltimorTASDK** [comment]
Are you certain that’s the issue? It’s not likely reshade would affect this.

**Comment by d0ob** [comment]
Oh hey there =) 
No indeed you're right ! Just tested and It's iGP11 that blocks it, I don't know why I assumed it was reshade...
_( https://www.nexusmods.com/darksouls3/mods/28 )_ Yeah it makes more sense now I think of it, iGP working as a launcher..
